# Generated by Django 4.0.2 on 2022-02-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('password', models.CharField(max_length=254)),
                ('phone_number', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('password', models.CharField(max_length=254)),
                ('phone_number', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('rate_per_hour', models.IntegerField(default=0)),
            ],
        ),
    ]
