# Generated by Django 4.0.2 on 2022-03-02 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_administration_delete_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
        migrations.RemoveField(
            model_name='workers',
            name='email',
        ),
    ]
