# Generated by Django 4.0.2 on 2022-03-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_remove_users_email_remove_workers_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='phone_number',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='workers',
            name='rate_per_hour',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
