# Generated by Django 4.0.2 on 2022-03-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_workers_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='administration',
            name='password',
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='administration',
            name='phone_number',
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='workers',
            name='password',
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='workers',
            name='phone_number',
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='workers',
            name='rate_per_hour',
            field=models.IntegerField(default=0),
        ),
    ]
