# Generated by Django 4.0.2 on 2022-03-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_alter_administration_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='administration',
            name='password',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='administration',
            name='phone_number',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='workers',
            name='password',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='workers',
            name='phone_number',
            field=models.CharField(max_length=254),
        ),
    ]
