# Generated by Django 4.0.2 on 2022-03-09 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0003_alter_schedule_worker'),
        ('Users', '0007_alter_administration_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administration',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.DeleteModel(
            name='Workers',
        ),
    ]
