# Generated by Django 4.0.2 on 2022-03-01 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0003_administration_delete_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hours_from', models.DecimalField(decimal_places=2, default=9.0, max_digits=4)),
                ('hours_until', models.DecimalField(decimal_places=2, default=23.3, max_digits=4)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.workers')),
            ],
        ),
    ]
