# Generated by Django 4.0.2 on 2022-03-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='hours_from',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='hours_until',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
