# Generated by Django 4.0.2 on 2022-02-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0002_alter_schedule_worker_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='worker_name',
            field=models.CharField(max_length=254),
        ),
    ]
