# Generated by Django 4.0.2 on 2022-03-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0003_alter_schedule_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='data',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='hours_from',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='hours_until',
        ),
        migrations.AddField(
            model_name='schedule',
            name='date_from',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='date_to',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='delta',
            field=models.IntegerField(default=0),
        ),
    ]
