# Generated by Django 4.0.2 on 2022-03-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0004_remove_schedule_data_remove_schedule_hours_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='date_to',
        ),
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='time_from',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='time_to',
            field=models.TimeField(null=True),
        ),
    ]
