# Generated by Django 4.0.2 on 2022-02-14 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0004_alter_schedule_worker_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='worker_name',
            new_name='worker',
        ),
    ]
