# Generated by Django 4.0.2 on 2022-02-15 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_rename_products_production'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Products.suppliers')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Products.suppliers')),
            ],
        ),
    ]
