# Generated by Django 4.0.2 on 2022-02-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_supply_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='is_active',
            field=models.BooleanField(null=True),
        ),
    ]
