# Generated by Django 4.0.2 on 2022-02-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_suppliers_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers',
            name='payment_deferment',
            field=models.IntegerField(),
        ),
    ]
