# Generated by Django 4.0.2 on 2022-02-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_alter_suppliers_payment_deferment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers',
            name='payment_deferment',
            field=models.IntegerField(default=0),
        ),
    ]
