# Generated by Django 4.0.2 on 2022-03-01 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_alter_suppliers_payment_deferment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.suppliers'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.suppliers'),
        ),
    ]
