# Generated by Django 4.0.2 on 2022-03-05 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_alter_bid_supplier_alter_supply_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliers',
            name='is_active',
        ),
    ]
