# Generated by Django 4.0.2 on 2022-03-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_remove_suppliers_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='supplier',
        ),
        migrations.AddField(
            model_name='bid',
            name='data',
            field=models.DateField(default='2022-03-08'),
        ),
    ]
