# Generated by Django 4.0.2 on 2022-03-08 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_delete_supply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.suppliers')),
            ],
        ),
    ]
